# Generated by Django 5.2.5 on 2025-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.CharField(verbose_name='内容')),
                ('total_views', models.IntegerField(default=0, verbose_name='总阅读数')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='用户人次')),
                ('pub_date', models.DateTimeField(verbose_name='发布日期')),
            ],
        ),
    ]
