# Generated by Django 5.2.5 on 2025-08-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.CreateModel(
            name='UserArticleViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='每人对应的阅读次数')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            options={
                'db_table': 'user_article_views',
                'indexes': [models.Index(fields=['article', 'user'], name='user_articl_article_69ddf2_idx'), models.Index(fields=['user'], name='user_articl_user_id_ce72a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_view')],
            },
        ),
    ]
