# Generated by Django 5.2.5 on 2025-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_alter_articles_pub_date_userarticleviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='热门文章'),
        ),
    ]
